import { describe, it, expect } from "vitest";
import { parseRecipeTree } from "./parseRecipeTree";
import { Node } from "@/hooks";
import { nanoid } from "nanoid";
import { Depth } from "./../../../lib";
import { Craft, Recipe } from "@/openapi";

describe("tree reducer test", () => {
	describe("toggle name", () => {
		const spec: Craft = {
			recipeId: "7058bc49df4",
			itemId: "63ab375b52f",
			name: "オールドキングダム・ガンブレード",
			pieces: 1,
			job: "鍛冶師",
			itemLevel: 710,
			craftLevel: null,
		};

		const tree: Recipe = {
			recipeId: "7058bc49df4",
			itemId: "63ab375b52f",
			job: "鍛冶師",
			pieces: 1,
			materials: [
				{
					itemId: "e8ccb4b1f81",
					itemName: "ファイアクラスター",
					quantity: 3,
					type: "crystal",
					recipes: [],
				},
				{
					itemId: "c97c6825890",
					itemName: "アースクラスター",
					quantity: 3,
					type: "crystal",
					recipes: [],
				},
				{
					itemId: "0975c5177af",
					itemName: "マルエージングインゴット",
					quantity: 3,
					type: "material",
					recipes: [
						{
							recipeId: "3051a1b2ec5",
							itemId: "0975c5177af",
							job: "鍛冶師",
							pieces: 1,
							materials: [
								{
									itemId: "e8ccb4b1f81",
									itemName: "ファイアクラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "c97c6825890",
									itemName: "アースクラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "43234377d42",
									itemName: "混鉄鉱",
									quantity: 4,
									type: "material",
									recipes: [],
								},
								{
									itemId: "369d97dd62c",
									itemName: "冷却触媒",
									quantity: 2,
									type: "material",
									recipes: [],
								},
							],
						},
						{
							recipeId: "72a9254ce03",
							itemId: "0975c5177af",
							job: "甲冑師",
							pieces: 1,
							materials: [
								{
									itemId: "4dbe0ec0a76",
									itemName: "アイスクラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "c97c6825890",
									itemName: "アースクラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "43234377d42",
									itemName: "混鉄鉱",
									quantity: 4,
									type: "material",
									recipes: [],
								},
								{
									itemId: "369d97dd62c",
									itemName: "冷却触媒",
									quantity: 2,
									type: "material",
									recipes: [],
								},
							],
						},
					],
				},
				{
					itemId: "a422d22ecdd",
					itemName: "スターリングシルバーインゴット",
					quantity: 2,
					type: "material",
					recipes: [
						{
							recipeId: "ac61907249f",
							itemId: "a422d22ecdd",
							job: "彫金師",
							pieces: 1,
							materials: [
								{
									itemId: "b61cbfd2d6e",
									itemName: "ウィンドクラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "e8ccb4b1f81",
									itemName: "ファイアクラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "7e15220ac85",
									itemName: "真銀鉱",
									quantity: 4,
									type: "material",
									recipes: [],
								},
								{
									itemId: "0828cd8b1ce",
									itemName: "壺匠の研磨剤",
									quantity: 2,
									type: "material",
									recipes: [],
								},
							],
						},
					],
				},
				{
					itemId: "5c7873bf132",
					itemName: "カザナルインゴット",
					quantity: 1,
					type: "material",
					recipes: [
						{
							recipeId: "4a9114f4319",
							itemId: "5c7873bf132",
							job: "甲冑師",
							pieces: 1,
							materials: [
								{
									itemId: "2d800a06851",
									itemName: "アイスクリスタル",
									quantity: 8,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "8f0a1f5272d",
									itemName: "黒鉄鉱",
									quantity: 5,
									type: "material",
									recipes: [],
								},
								{
									itemId: "5150c8a7261",
									itemName: "マグネシア粉",
									quantity: 1,
									type: "material",
									recipes: [],
								},
							],
						},
						{
							recipeId: "63ee02dc312",
							itemId: "5c7873bf132",
							job: "鍛冶師",
							pieces: 1,
							materials: [
								{
									itemId: "75403105d7f",
									itemName: "ファイアクリスタル",
									quantity: 8,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "8f0a1f5272d",
									itemName: "黒鉄鉱",
									quantity: 5,
									type: "material",
									recipes: [],
								},
								{
									itemId: "5150c8a7261",
									itemName: "マグネシア粉",
									quantity: 1,
									type: "material",
									recipes: [],
								},
							],
						},
					],
				},
				{
					itemId: "37508e7e63e",
					itemName: "活力の宝水G2",
					quantity: 2,
					type: "material",
					recipes: [
						{
							recipeId: "318ae51d75d",
							itemId: "37508e7e63e",
							job: "錬金術師",
							pieces: 3,
							materials: [
								{
									itemId: "e3d82488f80",
									itemName: "ウォータークラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "06061fd121b",
									itemName: "ライトニングクラスター",
									quantity: 3,
									type: "crystal",
									recipes: [],
								},
								{
									itemId: "f83d66bf883",
									itemName: "ノパルフラワー",
									quantity: 1,
									type: "material",
									recipes: [],
								},
								{
									itemId: "081882baa00",
									itemName: "ヤクテル天然水",
									quantity: 1,
									type: "material",
									recipes: [],
								},
								{
									itemId: "d628361c1fb",
									itemName: "ウィンドローレル",
									quantity: 1,
									type: "material",
									recipes: [],
								},
								{
									itemId: "ba8d1421da3",
									itemName: "黄金の霊砂",
									quantity: 1,
									type: "material",
									recipes: [],
								},
							],
						},
					],
				},
				{
					itemId: "37cc2eea408",
					itemName: "幻葉の霊砂",
					quantity: 1,
					type: "material",
					recipes: [],
				},
			],
		};

		const depth = {
			x: new Depth(),
			y: new Depth(),
		};

		const root: Node = {
			id: nanoid(),
			type: "childNode",
			data: {
				nodeType: "root",
				itemType: "material",
				itemId: spec.itemId,
				itemName: spec.name,
				pieces: spec.pieces,
				unit: spec.pieces,
				quantity: 1,
				source: "",
				depth: { x: depth.x.getDepth(), y: depth.y.getDepth() },
			},
			position: {
				x: 0,
				y: 0,
			},
		};

		const expectNodes: Node[] = [
			{
				id: "Td1M-U-1F20dEJvXyzdcb",
				type: "childNode",
				data: {
					nodeType: "root",
					itemId: "63ab375b52f",
					itemName: "オールドキングダム・ガンブレード",
					pieces: 1,
					unit: 1,
					quantity: 1,
					depth: { x: 0, y: 0 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 0,
					y: 0,
				},
			},
			{
				id: "cPh8lq-gV0CmhIDJ8bOQ3",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "e8ccb4b1f81",
					itemName: "ファイアクラスター",
					pieces: 0,
					unit: 3,
					quantity: 3,
					depth: { x: 1, y: 0 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 380,
					y: 0,
				},
			},
			{
				id: "chZK7peHiEY_WX4SM-UYF",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "c97c6825890",
					itemName: "アースクラスター",
					pieces: 0,
					unit: 3,
					quantity: 3,
					depth: { x: 1, y: 1 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 380,
					y: 140,
				},
			},
			{
				id: "Q32JYx4xAEXPekDsjDzpm",
				type: "childNode",
				data: {
					nodeType: "internal",
					itemId: "0975c5177af",
					itemName: "マルエージングインゴット",
					pieces: 1,
					unit: 3,
					quantity: 3,
					depth: { x: 1, y: 2 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 380,
					y: 280,
				},
			},
			{
				id: "i6c4s3eTxGzVqxxYgvXig",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "e8ccb4b1f81",
					itemName: "ファイアクラスター",
					pieces: 0,
					unit: 3,
					quantity: 9,
					depth: { x: 2, y: 2 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 760,
					y: 280,
				},
			},
			{
				id: "rckfr7MTRSVA-4zELaBSy",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "c97c6825890",
					itemName: "アースクラスター",
					pieces: 0,
					unit: 3,
					quantity: 9,
					depth: { x: 2, y: 3 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 760,
					y: 420,
				},
			},
			{
				id: "hyCI3dJ03bhpvqQvUiYBi",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "43234377d42",
					itemName: "混鉄鉱",
					pieces: 0,
					unit: 4,
					quantity: 12,
					depth: { x: 2, y: 4 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 560,
				},
			},
			{
				id: "NBRKlKwMG1ss-r3lV-QFW",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "369d97dd62c",
					itemName: "冷却触媒",
					pieces: 0,
					unit: 2,
					quantity: 6,
					depth: { x: 2, y: 5 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 700,
				},
			},
			{
				id: "ICNvqXtCV5ge0eyq3sRYM",
				type: "childNode",
				data: {
					nodeType: "internal",
					itemId: "a422d22ecdd",
					itemName: "スターリングシルバーインゴット",
					pieces: 1,
					unit: 2,
					quantity: 2,
					depth: { x: 1, y: 6 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 380,
					y: 840,
				},
			},
			{
				id: "kfYvY-9u0YRoqTSPSsVaz",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "b61cbfd2d6e",
					itemName: "ウィンドクラスター",
					pieces: 0,
					unit: 3,
					quantity: 6,
					depth: { x: 2, y: 6 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 760,
					y: 840,
				},
			},
			{
				id: "khW-hTGDXC-YAVZhIbkp4",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "e8ccb4b1f81",
					itemName: "ファイアクラスター",
					pieces: 0,
					unit: 3,
					quantity: 6,
					depth: { x: 2, y: 7 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 760,
					y: 980,
				},
			},
			{
				id: "UEELqn4rdGRZ_hANLu30o",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "7e15220ac85",
					itemName: "真銀鉱",
					pieces: 0,
					unit: 4,
					quantity: 8,
					depth: { x: 2, y: 8 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 1120,
				},
			},
			{
				id: "tSnnOvC4bQwPKlTa-5D48",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "0828cd8b1ce",
					itemName: "壺匠の研磨剤",
					pieces: 0,
					unit: 2,
					quantity: 4,
					depth: { x: 2, y: 9 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 1260,
				},
			},
			{
				id: "G-AavOwnvaqshRUAZFqRD",
				type: "childNode",
				data: {
					nodeType: "internal",
					itemId: "5c7873bf132",
					itemName: "カザナルインゴット",
					pieces: 1,
					unit: 1,
					quantity: 1,
					depth: { x: 1, y: 10 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 380,
					y: 1400,
				},
			},
			{
				id: "oHM2Owm2-COfm6i3N5MQy",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "2d800a06851",
					itemName: "アイスクリスタル",
					pieces: 0,
					unit: 8,
					quantity: 8,
					depth: { x: 2, y: 10 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 760,
					y: 1400,
				},
			},
			{
				id: "ecGBEOYTy8vtE2h7ko6EE",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "8f0a1f5272d",
					itemName: "黒鉄鉱",
					pieces: 0,
					unit: 5,
					quantity: 5,
					depth: { x: 2, y: 11 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 1540,
				},
			},
			{
				id: "R8lKHZlrhk0uq9IODCXtA",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "5150c8a7261",
					itemName: "マグネシア粉",
					pieces: 0,
					unit: 1,
					quantity: 1,
					depth: { x: 2, y: 12 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 1680,
				},
			},
			{
				id: "SJCGTCHsliQjrcHvGWuM6",
				type: "childNode",
				data: {
					nodeType: "internal",
					itemId: "37508e7e63e",
					itemName: "活力の宝水G2",
					pieces: 3,
					unit: 2,
					quantity: 2,
					depth: { x: 1, y: 13 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 380,
					y: 1820,
				},
			},
			{
				id: "ZtRbW8rsyPnSAgbYmxLjN",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "e3d82488f80",
					itemName: "ウォータークラスター",
					pieces: 0,
					unit: 3,
					quantity: 3,
					depth: { x: 2, y: 13 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 760,
					y: 1820,
				},
			},
			{
				id: "7nImAOiCPHxonI41mOIE7",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "06061fd121b",
					itemName: "ライトニングクラスター",
					pieces: 0,
					unit: 3,
					quantity: 3,
					depth: { x: 2, y: 14 },
					source: "",
					itemType: "crystal",
				},
				position: {
					x: 760,
					y: 1960,
				},
			},
			{
				id: "7dSQ1kvqQj6PUOdpdkZ-L",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "f83d66bf883",
					itemName: "ノパルフラワー",
					pieces: 0,
					unit: 1,
					quantity: 1,
					depth: { x: 2, y: 15 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 2100,
				},
			},
			{
				id: "ejNf5p4JmpaSOQepLV1Dz",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "081882baa00",
					itemName: "ヤクテル天然水",
					pieces: 0,
					unit: 1,
					quantity: 1,
					depth: { x: 2, y: 16 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 2240,
				},
			},
			{
				id: "W29Pjw-b_Ko2F504hQkSD",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "d628361c1fb",
					itemName: "ウィンドローレル",
					pieces: 0,
					unit: 1,
					quantity: 1,
					depth: { x: 2, y: 17 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 2380,
				},
			},
			{
				id: "MjOMSDk7M7j1YiawVzRQv",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "ba8d1421da3",
					itemName: "黄金の霊砂",
					pieces: 0,
					unit: 1,
					quantity: 1,
					depth: { x: 2, y: 18 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 760,
					y: 2520,
				},
			},
			{
				id: "_doW9am0EqlSnutjqawCx",
				type: "childNode",
				data: {
					nodeType: "leaf",
					itemId: "37cc2eea408",
					itemName: "幻葉の霊砂",
					pieces: 0,
					unit: 1,
					quantity: 1,
					depth: { x: 1, y: 19 },
					source: "",
					itemType: "material",
				},
				position: {
					x: 380,
					y: 2660,
				},
			},
		];

		const { nodes } = parseRecipeTree(tree, root, depth);

		it("test.name", () => {
			// idの値はランダム値なので除外して比較
			const actualData = [root, ...nodes].map(({ id, ...rest }) => rest);
			const expectData = expectNodes.map(({ id, ...rest }) => rest);
			expect(actualData).toEqual(expectData);
		});
	});
});
