import "@mantine/core/styles.css";
import '@xyflow/react/dist/style.css';
import { ThemeProvider } from "@/component/containers";
import { ColorSchemeScript } from "@mantine/core";
import { FC } from "react";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { theme } from "@/lib/theme";

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = {
	children: ReactNode;
};

const RootLayout: FC<Props> = ({ children }) => (
	<html lang="en">
		<head>
			<ColorSchemeScript defaultColorScheme="light" />
		</head>
		<body>
			<ThemeProvider defaultColorScheme="light" theme={theme}>
				{children}
			</ThemeProvider>
		</body>
	</html>
);

export default RootLayout;
export { metadata };
